[package]
name = "annuma"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
heck = "0.4"
reqwest = "0.11"
scraper = "0.17"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"