pub trait CommuneExt {
    fn code_postal(&self) -> &'static str;
}
#[derive(Debug, clap::Subcommand, strum::Display)]
pub enum Department {
    #[clap(about = "1-Ain")]
    Ain { #[arg(value_enum)] commune: Ain },
    #[clap(about = "2-Aisne")]
    Aisne { #[arg(value_enum)] commune: Aisne },
}
impl Department {
    pub fn number(&self) -> u32 {
        match self {
            Department::Ain { .. } => 1u32,
            Department::Aisne { .. } => 2u32,
        }
    }
    pub fn commune(&self) -> Box<&dyn std::fmt::Display> {
        match self {
            Department::Ain { commune } => Box::new(commune),
            Department::Aisne { commune } => Box::new(commune),
        }
    }
    pub fn code_postal(&self) -> &'static str {
        match self {
            Department::Ain { commune } => commune.code_postal(),
            Department::Aisne { commune } => commune.code_postal(),
        }
    }
}
#[derive(Debug, Copy, Clone, clap::ValueEnum, strum::Display)]
pub enum Ain {
    AbergementClemenciat,
    AbergementDeVarey,
    AmberieuEnBugey,
    AmberieuxEnDombes,
    Ambleon,
    Ambronay,
    Ambutrix,
    AndertEtCondon,
    Anglefort,
    Apremont,
    Aranc,
    Arandas,
    Arbent,
    ArboysEnBugey,
    Arbigny,
    Argis,
    Armix,
    ArsSurFormans,
    Artemare,
    AsnieresSurSaone,
    Attignat,
    BageDommartin,
    BageLeChatel,
    Balan,
    Baneins,
    Beaupont,
    Beauregard,
    Bellignat,
    Beligneux,
    BellegardeSurValserine,
    Belley,
    Belleydoux,
    BelmontLuthezieu,
    Benonces,
    Beny,
    Beon,
    Bereziat,
    Bettant,
    Bey,
    Beynost,
    Billiat,
    Birieux,
    Biziat,
    Blyes,
    Boisse,
    Boissey,
    Bolozon,
    Bouligneux,
    BourgEnBresse,
    BourgSaintChristophe,
    BoyeuxSaintJerome,
    Boz,
    BregnierCordon,
    Brenaz,
    Brenod,
    Brens,
    Bressolles,
    Brion,
    Briord,
    Buellas,
    Burbanche,
    Ceignes,
    Cerdon,
    Certines,
    Cessy,
    Ceyzeriat,
    Ceyzerieu,
    Chalamont,
    Chaleins,
    Chaley,
    ChallesLaMontagne,
    Challex,
    ChampagneEnValromey,
    ChampdorCorcelles,
    Champfromier,
    Chanay,
    Chaneins,
    ChanozChatenay,
    ChapelleDuChatelard,
    Charix,
    CharnozSurAin,
    ChateauGaillard,
    Chatenay,
    ChatillonEnMichaille,
    ChatillonLaPalud,
    ChatillonSurChalaronne,
    ChavannesSurReyssouze,
    NivigneEtSuran,
    Chaveyriat,
    Chavornay,
    ChazeyBons,
    ChazeySurAin,
    CheignieuLaBalme,
    Chevillard,
    Chevroux,
    Chevry,
    ChezeryForens,
    Civrieux,
    Cize,
    Cleyzieu,
    Coligny,
    Collonges,
    Colomieu,
    Conand,
    Condamine,
    Condeissiat,
    Confort,
    Confrancon,
    Contrevoz,
    Conzieu,
    Corbonod,
    Corlier,
    CormarancheEnBugey,
    CormorancheSurSaone,
    Cormoz,
    Corveissiat,
    Courmangoux,
    Courtes,
    Crans,
    CrasSurReyssouze,
    CressinRochefort,
    Crottet,
    Crozet,
    CruzillesLesMepillat,
    Culoz,
    CurciatDongalon,
    Curtafond,
    Cuzieu,
    Dagneux,
    DivonneLesBains,
    Dommartin,
    DompierreSurVeyle,
    DompierreSurChalaronne,
    Domsure,
    Dortan,
    Douvres,
    Drom,
    Druillat,
    Challon,
    Chenevex,
    Trez,
    Vosges,
    Faramans,
    Fareins,
    Farges,
    Feillens,
    FerneyVoltaire,
    Flaxieu,
    Foissiat,
    Francheleins,
    Frans,
    Garnerans,
    Genouilleux,
    BeardGeovreissiat,
    Geovreisset,
    Germagnat,
    Gex,
    Giron,
    Gorrevod,
    GrandCorent,
    Grieges,
    Grilly,
    Groissiat,
    Guereins,
    HautecourtRomaneche,
    HautevilleLompnes,
    Hostiaz,
    HautValromey,
    Illiat,
    InjouxGenissiat,
    Innimond,
    Izenave,
    Izernore,
    Izieu,
    JassansRiottier,
    Jasseron,
    Jayat,
    Journans,
    Joyeux,
    Jujurieux,
    Labalme,
    Lagnieu,
    Laiz,
    PoizatLalleyriat,
    Lancrans,
    Lantenay,
    Lapeyrouse,
    Lavours,
    Leaz,
    Lelex,
    Lent,
    Lescheroux,
    Leyment,
    Leyssard,
    Lhopital,
    Lhuis,
    Lochieu,
    Lompnas,
    Lompnieu,
    Loyettes,
    Lurcy,
    Magnieu,
    Maillat,
    Malafretaz,
    MantenayMontlin,
    Manziat,
    Marboz,
    Marchamp,
    Marignieu,
    Marlieux,
    Marsonnas,
    Martignat,
    Massieux,
    MassignieuDeRives,
    MatafelonGranges,
    Meillonnas,
    Merignat,
    MessimySurSaone,
    Meximieux,
    BohasMeyriatRignat,
    Mezeriat,
    Mijoux,
    Mionnay,
    Miribel,
    Miserieux,
    Mogneneins,
    Montagnat,
    Montagnieu,
    Montanges,
    Montceaux,
    Montcet,
    Montellier,
    Monthieux,
    Montluel,
    MontmerleSurSaone,
    Montracol,
    MontrealLaCluse,
    MontrevelEnBresse,
    NurieuxVolognat,
    MursEtGelignieux,
    Nantua,
    NeuvilleLesDames,
    NeuvilleSurAin,
    Neyrolles,
    Neyron,
    Nievroz,
    NivolletMontgriffon,
    Oncieu,
    Ordonnaz,
    Ornex,
    Outriaz,
    Oyonnax,
    Ozan,
    Parcieux,
    ParvesEtNattages,
    Peron,
    Peronnas,
    Perouges,
    Perrex,
    Peyriat,
    Peyrieu,
    PeyzieuxSurSaone,
    Pirajoux,
    Pizay,
    Plagne,
    Plantay,
    Polliat,
    Pollieu,
    Poncin,
    PontDAin,
    PontDeVaux,
    PontDeVeyle,
    Port,
    Pougny,
    Pouillat,
    Premeyzel,
    Premillieu,
    PrevessinMoens,
    Priay,
    Pugieu,
    Ramasse,
    Rance,
    Relevant,
    Replonges,
    Revonnas,
    Reyrieux,
    Reyssouze,
    RignieuxLeFranc,
    Romans,
    Rossillon,
    Ruffieu,
    SaintAlban,
    SaintAndreDeBage,
    SaintAndreDeCorcy,
    SaintAndreDHuiriat,
    SaintAndreLeBouchoux,
    SaintAndreSurVieuxJonc,
    SaintBenigne,
    GrosleeSaintBenoit,
    SaintBernard,
    SaintChamp,
    SainteCroix,
    SaintCyrSurMenthon,
    SaintDenisLesBourg,
    SaintDenisEnBugey,
    SaintDidierDAussiat,
    SaintDidierDeFormans,
    SaintDidierSurChalaronne,
    SaintLoi,
    SaintTienneDuBois,
    SaintTienneSurChalaronne,
    SaintTienneSurReyssouze,
    SainteEuphemie,
    SaintGenisPouilly,
    SaintGenisSurMenthon,
    SaintGeorgesSurRenon,
    SaintGermainDeJoux,
    SaintGermainLesParoisses,
    SaintGermainSurRenon,
    SaintJeanDeGonville,
    SaintJeanDeNiost,
    SaintJeanDeThurigneux,
    SaintJeanLeVieux,
    SaintJeanSurReyssouze,
    SaintJeanSurVeyle,
    SainteJulie,
    SaintJulienSurReyssouze,
    SaintJulienSurVeyle,
    SaintJust,
    SaintLaurentSurSaone,
    SaintMarcel,
    SaintMartinDeBavel,
    SaintMartinDuFrene,
    SaintMartinDuMont,
    SaintMartinLeChatel,
    SaintMauriceDeBeynost,
    SaintMauriceDeGourdans,
    SaintMauriceDeRemens,
    SaintNizierLeBouchoux,
    SaintNizierLeDesert,
    SainteOlive,
    SaintPaulDeVarax,
    SaintRambertEnBugey,
    SaintRemy,
    SaintSorlinEnBugey,
    SaintSulpice,
    SaintTrivierDeCourtes,
    SaintTrivierSurMoignans,
    SaintVulbas,
    Salavre,
    Samognat,
    Sandrans,
    SaultBrenaz,
    Sauverny,
    Savigneux,
    Segny,
    Seillonnaz,
    Sergy,
    Sermoyer,
    SerrieresDeBriord,
    SerrieresSurAin,
    Servas,
    Servignat,
    Seyssel,
    SimandreSurSuran,
    SonthonnaxLaMontagne,
    Souclin,
    Sulignat,
    Surjoux,
    Sutrieu,
    Talissieu,
    Tenay,
    Thezillieu,
    Thil,
    Thoiry,
    Thoissey,
    Torcieu,
    Tossiat,
    Toussieux,
    Tramoyes,
    Trancliere,
    ValRevermont,
    Trevoux,
    Valeins,
    Vandeins,
    Varambon,
    VauxEnBugey,
    Verjon,
    Vernoux,
    Versailleux,
    Versonnex,
    Vesancy,
    Vescours,
    Vesines,
    VieuDIzenave,
    Vieu,
    VillarsLesDombes,
    Villebois,
    Villemotier,
    Villeneuve,
    Villereversure,
    Villes,
    VilletteSurAin,
    VillieuLoyesMollon,
    Viriat,
    VirieuLeGrand,
    VirieuLePetit,
    Virignin,
    Vongnes,
    Vonnas,
}
impl CommuneExt for Ain {
    fn code_postal(&self) -> &'static str {
        match self {
            Self::AbergementClemenciat => "1400",
            Self::AbergementDeVarey => "1640",
            Self::AmberieuEnBugey => "1500",
            Self::AmberieuxEnDombes => "1330",
            Self::Ambleon => "1300",
            Self::Ambronay => "1500",
            Self::Ambutrix => "1500",
            Self::AndertEtCondon => "1300",
            Self::Anglefort => "1350",
            Self::Apremont => "1100",
            Self::Aranc => "1110",
            Self::Arandas => "1230",
            Self::Arbent => "1100",
            Self::ArboysEnBugey => "1300",
            Self::Arbigny => "1190",
            Self::Argis => "1230",
            Self::Armix => "1510",
            Self::ArsSurFormans => "1480",
            Self::Artemare => "1510",
            Self::AsnieresSurSaone => "1570",
            Self::Attignat => "1340",
            Self::BageDommartin => "1380",
            Self::BageLeChatel => "1380",
            Self::Balan => "1360",
            Self::Baneins => "1990",
            Self::Beaupont => "1270",
            Self::Beauregard => "1480",
            Self::Bellignat => "1100",
            Self::Beligneux => "1360",
            Self::BellegardeSurValserine => "1200",
            Self::Belley => "1300",
            Self::Belleydoux => "1130",
            Self::BelmontLuthezieu => "1260",
            Self::Benonces => "1470",
            Self::Beny => "1370",
            Self::Beon => "1350",
            Self::Bereziat => "1340",
            Self::Bettant => "1500",
            Self::Bey => "1290",
            Self::Beynost => "1700",
            Self::Billiat => "1200",
            Self::Birieux => "1330",
            Self::Biziat => "1290",
            Self::Blyes => "1150",
            Self::Boisse => "1120",
            Self::Boissey => "1190",
            Self::Boissey => "1380",
            Self::Bolozon => "1450",
            Self::Bouligneux => "1330",
            Self::BourgEnBresse => "1000",
            Self::BourgSaintChristophe => "1800",
            Self::BoyeuxSaintJerome => "1640",
            Self::Boz => "1190",
            Self::BregnierCordon => "1300",
            Self::Brenaz => "1260",
            Self::Brenod => "1110",
            Self::Brens => "1300",
            Self::Bressolles => "1360",
            Self::Brion => "1460",
            Self::Briord => "1470",
            Self::Buellas => "1310",
            Self::Burbanche => "1510",
            Self::Ceignes => "1430",
            Self::Cerdon => "1450",
            Self::Certines => "1240",
            Self::Cessy => "1170",
            Self::Ceyzeriat => "1250",
            Self::Ceyzerieu => "1350",
            Self::Chalamont => "1320",
            Self::Chaleins => "1480",
            Self::Chaley => "1230",
            Self::ChallesLaMontagne => "1450",
            Self::Challex => "1630",
            Self::ChampagneEnValromey => "1260",
            Self::ChampdorCorcelles => "1110",
            Self::Champfromier => "1410",
            Self::Chanay => "1420",
            Self::Chaneins => "1990",
            Self::ChanozChatenay => "1400",
            Self::ChapelleDuChatelard => "1240",
            Self::Charix => "1130",
            Self::CharnozSurAin => "1800",
            Self::ChateauGaillard => "1500",
            Self::Chatenay => "1320",
            Self::ChatillonEnMichaille => "1200",
            Self::ChatillonLaPalud => "1320",
            Self::ChatillonSurChalaronne => "1400",
            Self::ChavannesSurReyssouze => "1190",
            Self::NivigneEtSuran => "1250",
            Self::Chaveyriat => "1660",
            Self::Chavornay => "1510",
            Self::ChazeyBons => "1300",
            Self::ChazeySurAin => "1150",
            Self::CheignieuLaBalme => "1510",
            Self::Chevillard => "1430",
            Self::Chevroux => "1190",
            Self::Chevry => "1170",
            Self::ChezeryForens => "1200",
            Self::ChezeryForens => "1410",
            Self::Civrieux => "1390",
            Self::Cize => "1250",
            Self::Cleyzieu => "1230",
            Self::Coligny => "1270",
            Self::Collonges => "1550",
            Self::Colomieu => "1300",
            Self::Conand => "1230",
            Self::Condamine => "1430",
            Self::Condeissiat => "1400",
            Self::Confort => "1200",
            Self::Confrancon => "1310",
            Self::Contrevoz => "1300",
            Self::Conzieu => "1300",
            Self::Corbonod => "1420",
            Self::Corlier => "1110",
            Self::CormarancheEnBugey => "1110",
            Self::CormorancheSurSaone => "1290",
            Self::Cormoz => "1560",
            Self::Corveissiat => "1250",
            Self::Courmangoux => "1370",
            Self::Courtes => "1560",
            Self::Crans => "1320",
            Self::CrasSurReyssouze => "1340",
            Self::CressinRochefort => "1350",
            Self::Crottet => "1290",
            Self::Crottet => "1750",
            Self::Crozet => "1170",
            Self::CruzillesLesMepillat => "1290",
            Self::Culoz => "1350",
            Self::CurciatDongalon => "1560",
            Self::Curtafond => "1310",
            Self::Cuzieu => "1300",
            Self::Dagneux => "1120",
            Self::DivonneLesBains => "1220",
            Self::Dommartin => "1380",
            Self::DompierreSurVeyle => "1240",
            Self::DompierreSurChalaronne => "1400",
            Self::Domsure => "1270",
            Self::Dortan => "1590",
            Self::Douvres => "1500",
            Self::Drom => "1250",
            Self::Druillat => "1160",
            Self::Challon => "1130",
            Self::Chenevex => "1170",
            Self::Trez => "1340",
            Self::Vosges => "1230",
            Self::Faramans => "1800",
            Self::Fareins => "1480",
            Self::Farges => "1550",
            Self::Feillens => "1570",
            Self::FerneyVoltaire => "1210",
            Self::Flaxieu => "1350",
            Self::Foissiat => "1340",
            Self::Francheleins => "1090",
            Self::Frans => "1480",
            Self::Garnerans => "1140",
            Self::Genouilleux => "1090",
            Self::BeardGeovreissiat => "1460",
            Self::Geovreisset => "1100",
            Self::Germagnat => "1250",
            Self::Gex => "1170",
            Self::Giron => "1130",
            Self::Gorrevod => "1190",
            Self::GrandCorent => "1250",
            Self::Grieges => "1290",
            Self::Grilly => "1220",
            Self::Groissiat => "1100",
            Self::Guereins => "1090",
            Self::HautecourtRomaneche => "1250",
            Self::HautevilleLompnes => "1110",
            Self::Hostiaz => "1110",
            Self::HautValromey => "1260",
            Self::Illiat => "1140",
            Self::InjouxGenissiat => "1200",
            Self::Innimond => "1680",
            Self::Izenave => "1430",
            Self::Izernore => "1580",
            Self::Izieu => "1300",
            Self::JassansRiottier => "1480",
            Self::Jasseron => "1250",
            Self::Jayat => "1340",
            Self::Journans => "1250",
            Self::Joyeux => "1800",
            Self::Jujurieux => "1640",
            Self::Labalme => "1450",
            Self::Lagnieu => "1150",
            Self::Laiz => "1290",
            Self::PoizatLalleyriat => "1130",
            Self::Lancrans => "1200",
            Self::Lantenay => "1430",
            Self::Lapeyrouse => "1330",
            Self::Lavours => "1350",
            Self::Leaz => "1200",
            Self::Lelex => "1410",
            Self::Lent => "1240",
            Self::Lescheroux => "1560",
            Self::Leyment => "1150",
            Self::Leyssard => "1450",
            Self::Lhopital => "1420",
            Self::Lhuis => "1680",
            Self::Lochieu => "1260",
            Self::Lompnas => "1680",
            Self::Lompnieu => "1260",
            Self::Loyettes => "1360",
            Self::Lurcy => "1090",
            Self::Magnieu => "1300",
            Self::Maillat => "1430",
            Self::Malafretaz => "1340",
            Self::MantenayMontlin => "1560",
            Self::Manziat => "1570",
            Self::Marboz => "1851",
            Self::Marchamp => "1680",
            Self::Marignieu => "1300",
            Self::Marlieux => "1240",
            Self::Marsonnas => "1340",
            Self::Martignat => "1100",
            Self::Massieux => "1600",
            Self::MassignieuDeRives => "1300",
            Self::MatafelonGranges => "1580",
            Self::Meillonnas => "1370",
            Self::Merignat => "1450",
            Self::MessimySurSaone => "1480",
            Self::Meximieux => "1800",
            Self::BohasMeyriatRignat => "1250",
            Self::Mezeriat => "1660",
            Self::Mijoux => "1170",
            Self::Mijoux => "1410",
            Self::Mionnay => "1390",
            Self::Miribel => "1700",
            Self::Miserieux => "1600",
            Self::Mogneneins => "1140",
            Self::Montagnat => "1250",
            Self::Montagnieu => "1470",
            Self::Montanges => "1200",
            Self::Montceaux => "1090",
            Self::Montcet => "1310",
            Self::Montellier => "1800",
            Self::Monthieux => "1390",
            Self::Montluel => "1120",
            Self::MontmerleSurSaone => "1090",
            Self::Montracol => "1310",
            Self::MontrealLaCluse => "1460",
            Self::MontrevelEnBresse => "1340",
            Self::NurieuxVolognat => "1460",
            Self::MursEtGelignieux => "1300",
            Self::Nantua => "1130",
            Self::Nantua => "1460",
            Self::NeuvilleLesDames => "1400",
            Self::NeuvilleSurAin => "1160",
            Self::Neyrolles => "1130",
            Self::Neyron => "1700",
            Self::Nievroz => "1120",
            Self::NivolletMontgriffon => "1230",
            Self::Oncieu => "1230",
            Self::Ordonnaz => "1510",
            Self::Ornex => "1210",
            Self::Outriaz => "1430",
            Self::Oyonnax => "1100",
            Self::Ozan => "1190",
            Self::Parcieux => "1600",
            Self::ParvesEtNattages => "1300",
            Self::Peron => "1630",
            Self::Peronnas => "1960",
            Self::Perouges => "1800",
            Self::Perrex => "1540",
            Self::Peyriat => "1430",
            Self::Peyrieu => "1300",
            Self::PeyzieuxSurSaone => "1140",
            Self::Pirajoux => "1270",
            Self::Pizay => "1120",
            Self::Plagne => "1130",
            Self::Plantay => "1330",
            Self::Polliat => "1310",
            Self::Pollieu => "1350",
            Self::Poncin => "1450",
            Self::PontDAin => "1160",
            Self::PontDeVaux => "1190",
            Self::PontDeVeyle => "1290",
            Self::Port => "1460",
            Self::Pougny => "1550",
            Self::Pouillat => "1250",
            Self::Premeyzel => "1300",
            Self::Premillieu => "1110",
            Self::PrevessinMoens => "1280",
            Self::Priay => "1160",
            Self::Pugieu => "1510",
            Self::Ramasse => "1250",
            Self::Rance => "1390",
            Self::Relevant => "1990",
            Self::Replonges => "1750",
            Self::Revonnas => "1250",
            Self::Reyrieux => "1600",
            Self::Reyssouze => "1190",
            Self::RignieuxLeFranc => "1800",
            Self::Romans => "1400",
            Self::Rossillon => "1510",
            Self::Ruffieu => "1260",
            Self::SaintAlban => "1450",
            Self::SaintAndreDeBage => "1380",
            Self::SaintAndreDeCorcy => "1390",
            Self::SaintAndreDHuiriat => "1290",
            Self::SaintAndreLeBouchoux => "1240",
            Self::SaintAndreSurVieuxJonc => "1960",
            Self::SaintBenigne => "1190",
            Self::GrosleeSaintBenoit => "1300",
            Self::GrosleeSaintBenoit => "1680",
            Self::SaintBernard => "1600",
            Self::SaintChamp => "1300",
            Self::SainteCroix => "1120",
            Self::SaintCyrSurMenthon => "1380",
            Self::SaintDenisLesBourg => "1000",
            Self::SaintDenisEnBugey => "1500",
            Self::SaintDidierDAussiat => "1340",
            Self::SaintDidierDeFormans => "1600",
            Self::SaintDidierSurChalaronne => "1140",
            Self::SaintLoi => "1800",
            Self::SaintTienneDuBois => "1370",
            Self::SaintTienneSurChalaronne => "1140",
            Self::SaintTienneSurReyssouze => "1190",
            Self::SainteEuphemie => "1600",
            Self::SaintGenisPouilly => "1630",
            Self::SaintGenisSurMenthon => "1380",
            Self::SaintGeorgesSurRenon => "1400",
            Self::SaintGermainDeJoux => "1130",
            Self::SaintGermainLesParoisses => "1300",
            Self::SaintGermainSurRenon => "1240",
            Self::SaintJeanDeGonville => "1630",
            Self::SaintJeanDeNiost => "1800",
            Self::SaintJeanDeThurigneux => "1390",
            Self::SaintJeanLeVieux => "1640",
            Self::SaintJeanSurReyssouze => "1560",
            Self::SaintJeanSurVeyle => "1290",
            Self::SainteJulie => "1150",
            Self::SaintJulienSurReyssouze => "1560",
            Self::SaintJulienSurVeyle => "1540",
            Self::SaintJust => "1250",
            Self::SaintLaurentSurSaone => "1750",
            Self::SaintMarcel => "1390",
            Self::SaintMartinDeBavel => "1510",
            Self::SaintMartinDuFrene => "1430",
            Self::SaintMartinDuMont => "1160",
            Self::SaintMartinLeChatel => "1310",
            Self::SaintMauriceDeBeynost => "1700",
            Self::SaintMauriceDeGourdans => "1800",
            Self::SaintMauriceDeRemens => "1500",
            Self::SaintNizierLeBouchoux => "1560",
            Self::SaintNizierLeDesert => "1320",
            Self::SainteOlive => "1330",
            Self::SaintPaulDeVarax => "1240",
            Self::SaintRambertEnBugey => "1230",
            Self::SaintRemy => "1310",
            Self::SaintSorlinEnBugey => "1150",
            Self::SaintSulpice => "1340",
            Self::SaintTrivierDeCourtes => "1560",
            Self::SaintTrivierSurMoignans => "1990",
            Self::SaintVulbas => "1150",
            Self::Salavre => "1270",
            Self::Samognat => "1580",
            Self::Sandrans => "1400",
            Self::SaultBrenaz => "1150",
            Self::Sauverny => "1220",
            Self::Savigneux => "1480",
            Self::Segny => "1170",
            Self::Seillonnaz => "1470",
            Self::Sergy => "1630",
            Self::Sermoyer => "1190",
            Self::SerrieresDeBriord => "1470",
            Self::SerrieresSurAin => "1450",
            Self::Servas => "1960",
            Self::Servignat => "1560",
            Self::Seyssel => "1420",
            Self::SimandreSurSuran => "1250",
            Self::SonthonnaxLaMontagne => "1580",
            Self::Souclin => "1150",
            Self::Sulignat => "1400",
            Self::Surjoux => "1420",
            Self::Sutrieu => "1260",
            Self::Talissieu => "1510",
            Self::Tenay => "1230",
            Self::Thezillieu => "1110",
            Self::Thil => "1120",
            Self::Thoiry => "1710",
            Self::Thoissey => "1140",
            Self::Torcieu => "1230",
            Self::Tossiat => "1250",
            Self::Toussieux => "1600",
            Self::Tramoyes => "1390",
            Self::Trancliere => "1160",
            Self::ValRevermont => "1370",
            Self::Trevoux => "1600",
            Self::Valeins => "1140",
            Self::Vandeins => "1660",
            Self::Varambon => "1160",
            Self::VauxEnBugey => "1150",
            Self::Verjon => "1270",
            Self::Vernoux => "1560",
            Self::Versailleux => "1330",
            Self::Versonnex => "1210",
            Self::Vesancy => "1170",
            Self::Vescours => "1560",
            Self::Vesines => "1570",
            Self::VieuDIzenave => "1430",
            Self::Vieu => "1260",
            Self::VillarsLesDombes => "1330",
            Self::Villebois => "1150",
            Self::Villemotier => "1270",
            Self::Villeneuve => "1480",
            Self::Villereversure => "1250",
            Self::Villes => "1200",
            Self::VilletteSurAin => "1320",
            Self::VillieuLoyesMollon => "1800",
            Self::Viriat => "1440",
            Self::VirieuLeGrand => "1510",
            Self::VirieuLePetit => "1260",
            Self::Virignin => "1300",
            Self::Vongnes => "1350",
            Self::Vonnas => "1540",
        }
    }
}
#[derive(Debug, Copy, Clone, clap::ValueEnum, strum::Display)]
pub enum Aisne {
    Abbecourt,
    Achery,
    Acy,
    AgnicourtEtSechelles,
    Aguilcourt,
    AisonvilleEtBernoville,
    Aizelles,
    AizyJouy,
    Alaincourt,
    Allemant,
    Ambleny,
    Ambrief,
    Amifontaine,
    AmignyRouy,
    Ancienville,
    Andelain,
    AnguilcourtLeSart,
    AnizyLeChateau,
    Annois,
    AnyMartinRieux,
    Archon,
    ArcySainteRestitue,
    ArmentieresSurOurcq,
    Arrancy,
    Artemps,
    AssisSurSerre,
    AthiesSousLaon,
    Attilly,
    AubencheulAuxBois,
    Aubenton,
    AubignyAuxKaisnes,
    AubignyEnLaonnois,
    Audignicourt,
    Audigny,
    Augy,
    AulnoisSousLaon,
    Autels,
    Autremencourt,
    Autreppes,
    Autreville,
    AzySurMarne,
    Bagneux,
    Bancigny,
    BarentonBugny,
    BarentonCel,
    BarentonSurSerre,
    BarisisAuxBois,
    BarzyEnThierache,
    BarzySurMarne,
    BassolesAulers,
    ValleesEnChampagne,
    BazochesSurVesles,
    Beaume,
    BeaumontEnBeine,
    Beaurevoir,
    Beaurieux,
    Beautor,
    BeauvoisEnVermandois,
    Becquigny,
    Belleau,
    Bellenglise,
    Belleu,
    Bellicourt,
    Benay,
    BerguesSurSambre,
    Berlancourt,
}
impl CommuneExt for Aisne {
    fn code_postal(&self) -> &'static str {
        match self {
            Self::Abbecourt => "2300",
            Self::Achery => "2800",
            Self::Acy => "2200",
            Self::AgnicourtEtSechelles => "2340",
            Self::Aguilcourt => "2190",
            Self::AisonvilleEtBernoville => "2110",
            Self::Aizelles => "2820",
            Self::AizyJouy => "2370",
            Self::Alaincourt => "2240",
            Self::Allemant => "2320",
            Self::Ambleny => "2290",
            Self::Ambrief => "2200",
            Self::Amifontaine => "2190",
            Self::AmignyRouy => "2700",
            Self::Ancienville => "2600",
            Self::Andelain => "2800",
            Self::AnguilcourtLeSart => "2800",
            Self::AnizyLeChateau => "2320",
            Self::Annois => "2480",
            Self::AnyMartinRieux => "2500",
            Self::Archon => "2360",
            Self::ArcySainteRestitue => "2130",
            Self::ArmentieresSurOurcq => "2210",
            Self::Arrancy => "2860",
            Self::Artemps => "2480",
            Self::AssisSurSerre => "2270",
            Self::AthiesSousLaon => "2840",
            Self::Attilly => "2490",
            Self::AubencheulAuxBois => "2420",
            Self::Aubenton => "2500",
            Self::AubignyAuxKaisnes => "2590",
            Self::AubignyEnLaonnois => "2820",
            Self::Audignicourt => "2300",
            Self::Audigny => "2120",
            Self::Augy => "2220",
            Self::AulnoisSousLaon => "2000",
            Self::Autels => "2360",
            Self::Autremencourt => "2250",
            Self::Autreppes => "2580",
            Self::Autreville => "2300",
            Self::AzySurMarne => "2400",
            Self::Bagneux => "2290",
            Self::Bancigny => "2140",
            Self::BarentonBugny => "2000",
            Self::BarentonCel => "2000",
            Self::BarentonSurSerre => "2270",
            Self::BarisisAuxBois => "2700",
            Self::BarzyEnThierache => "2170",
            Self::BarzySurMarne => "2850",
            Self::BassolesAulers => "2380",
            Self::ValleesEnChampagne => "2330",
            Self::BazochesSurVesles => "2220",
            Self::Beaume => "2500",
            Self::BeaumontEnBeine => "2300",
            Self::Beaurevoir => "2110",
            Self::Beaurieux => "2160",
            Self::Beautor => "2800",
            Self::BeauvoisEnVermandois => "2590",
            Self::Becquigny => "2110",
            Self::Belleau => "2400",
            Self::Bellenglise => "2420",
            Self::Belleu => "2200",
            Self::Bellicourt => "2420",
            Self::Benay => "2440",
            Self::BerguesSurSambre => "2450",
            Self::Berlancourt => "2250",
        }
    }
}
